version: '3.8'

services:
  flask-api:
    build: .
    working_dir: /app
    volumes:
      - .:/app
    command: sh -c "pip install --no-cache-dir -r requirements.txt && python app.py"
    ports:
      - "5000:5000"